# This image provides a Ruby environment you can use to run your Ruby
# applications.
FROM ubi9/s2i-base

EXPOSE 8080

ENV RUBY_VERSION="3.3"

ENV RUBY_SCL="ruby-33" \
    IMAGE_NAME="ubi9/ruby-33" \
    SUMMARY="Platform for building and running Ruby 3.3 applications." \
    DESCRIPTION="Ruby 3.3 available as container is a base platform for \
building and running various Ruby 3.3 applications and frameworks. \
Ruby is the interpreted scripting language for quick and easy object-oriented programming. \
It has many features to process text files and to do system management tasks (as in Perl). \
It is simple, straight-forward, and extensible."

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="Ruby 3.3" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,ruby,ruby33,ruby-33" \
      com.redhat.component="ruby-33-container" \
      name="ubi9/ruby-33" \
      version="1" \
      com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI" \
      usage="s2i build https://github.com/sclorg/s2i-ruby-container.git \
--context-dir=${RUBY_VERSION}/test/puma-test-app/ ${IMAGE_NAME} ruby-sample-app" \
      maintainer="SoftwareCollections.org <sclorg@redhat.com>"

RUN INSTALL_PKGS="ruby ruby-devel rubygem-rake rubygem-bundler ruby-bundled-gems redhat-rpm-config libffi-devel" && \
    dnf module enable -y ruby:3.3 && \
    dnf install -y --setopt=tsflags=nodocs ${INSTALL_PKGS} && \
    dnf -y clean all --enablerepo='*' && \
    ruby -v | grep -qe "^ruby $RUBY_VERSION\." && echo "Found VERSION $RUBY_VERSION" && \
    rpm -V ${INSTALL_PKGS}

# Copy the S2I scripts from the specific language image to $STI_SCRIPTS_PATH
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

# Copy extra files to the image.
COPY ./root/ /

# Drop the root user and make the content of /opt/app-root owned by user 1001
RUN chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT} && \
    rpm-file-permissions

USER 1001

# Set the default CMD to print the usage of the language image
CMD $STI_SCRIPTS_PATH/usage
