# This image provides a Ruby environment you can use to run your Ruby
# applications.
FROM quay.io/sclorg/s2i-base-c10s:c10s

EXPOSE 8080

ENV RUBY_VERSION="4.0"

ENV RUBY_SCL="ruby-40" \
    IMAGE_NAME="sclorg/ruby-40-c10s" \
    SUMMARY="Platform for building and running Ruby 4.0 applications." \
    DESCRIPTION="Ruby 4.0 available as container is a base platform for \
building and running various Ruby 4.0 applications and frameworks. \
Ruby is the interpreted scripting language for quick and easy object-oriented programming. \
It has many features to process text files and to do system management tasks (as in Perl). \
It is simple, straight-forward, and extensible."

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="Ruby 4.0" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,ruby,ruby40,ruby-40" \
      com.redhat.component="ruby-40-container" \
      name="sclorg/ruby-40-c10s" \
      version="1" \
      usage="s2i build https://github.com/sclorg/s2i-ruby-container.git \
--context-dir=${RUBY_VERSION}/test/puma-test-app/ ${IMAGE_NAME} ruby-sample-app" \
      maintainer="SoftwareCollections.org <sclorg@redhat.com>"

RUN INSTALL_PKGS="ruby4.0 ruby4.0-devel redhat-rpm-config libffi-devel" && \
    dnf install -y --setopt=tsflags=nodocs ${INSTALL_PKGS} && \
    dnf reinstall -y --setopt=tsflags=nodocs tzdata && \
    dnf -y clean all --enablerepo='*' && \
    ruby4.0 -v | grep -qe "^ruby $RUBY_VERSION\." && echo "Found VERSION $RUBY_VERSION" && \
    rpm -V ${INSTALL_PKGS}

# Symlink the binaries. Ruby now provides suffixed binaries in /usr/bin.
# Provide the non-suffixed version in the container.
RUN rpm -ql ruby4.0 ruby4.0-devel | \
      grep '/usr/bin' | \
      xargs --max-args=1 basename -s ${RUBY_VERSION} | \
      xargs -I{} ln -s "/usr/bin/{}${RUBY_VERSION}" "/usr/bin/{}"
# Copy the S2I scripts from the specific language image to $STI_SCRIPTS_PATH
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

# Copy extra files to the image.
COPY ./root/ /

# Drop the root user and make the content of /opt/app-root owned by user 1001
RUN chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT} && \
    rpm-file-permissions

USER 1001

# Set the default CMD to print the usage of the language image
CMD $STI_SCRIPTS_PATH/usage
