# This image provides a Ruby environment you can use to run your Ruby
# applications.
FROM {{ spec.s2i_base }}

EXPOSE 8080

ENV RUBY_VERSION="{{ spec.stream }}"

ENV RUBY_SCL="ruby-{{ spec.tag }}" \
    IMAGE_NAME="{{ spec.image_name }}" \
    SUMMARY="Platform for building and running Ruby {{ spec.stream }} applications." \
    DESCRIPTION="Ruby {{ spec.stream }} available as container is a base platform for \
building and running various Ruby {{ spec.stream }} applications and frameworks. \
Ruby is the interpreted scripting language for quick and easy object-oriented programming. \
It has many features to process text files and to do system management tasks (as in Perl). \
It is simple, straight-forward, and extensible."

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="Ruby {{ spec.stream }}" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="{{ spec.openshift_tags }}" \
      com.redhat.component="ruby-{{ spec.tag }}-container" \
      name="{{ spec.image_name }}" \
{% if config.os.id == "rhel" and config.os.version < 10 %}
      version="1" \
{% elif config.os.id == "centos-stream" %}
      version="1" \
{% elif config.os.id == "fedora" %}
      version="0" \
{% endif %}
{% if config.os.id == "rhel" %}
      com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI" \
{% endif %}
      usage="s2i build https://github.com/sclorg/s2i-ruby-container.git \
--context-dir=${RUBY_VERSION}/test/puma-test-app/ ${IMAGE_NAME} ruby-sample-app" \
      maintainer="SoftwareCollections.org <sclorg@redhat.com>"

{% if spec.base_ruby_rpm == spec.stream %}
RUN {{ spec.base_rpm_install }} && \
{% elif spec.has_modules %}
RUN {{ spec.alternative_module_install }} && \
{% else %}
RUN {{ spec.alternative_rpm_install }} && \
{% endif %}
{% if (config.os.id == "rhel" or config.os.id == "centos-stream") and config.os.version >= 10 %}
    dnf reinstall -y --setopt=tsflags=nodocs tzdata && \
{% endif %}
    dnf -y clean all --enablerepo='*' && \
{% if spec.has_modules or spec.base_ruby_rpm == spec.stream %}
    ruby -v | grep -qe "^ruby $RUBY_VERSION\." && echo "Found VERSION $RUBY_VERSION" && \
{% else %}
    ruby{{ spec.stream }} -v | grep -qe "^ruby $RUBY_VERSION\." && echo "Found VERSION $RUBY_VERSION" && \
{% endif %}
    rpm -V ${INSTALL_PKGS}

{% if not spec.has_modules and spec.base_ruby_rpm != spec.stream %}
# Symlink the binaries. Ruby now provides suffixed binaries in /usr/bin.
# Provide the non-suffixed version in the container.
RUN rpm -ql ruby{{ spec.stream }} ruby{{ spec.stream }}-devel | \
      grep '/usr/bin' | \
      xargs --max-args=1 basename -s ${RUBY_VERSION} | \
      xargs -I{} ln -s "/usr/bin/{}${RUBY_VERSION}" "/usr/bin/{}"
{% endif %}
# Copy the S2I scripts from the specific language image to $STI_SCRIPTS_PATH
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

# Copy extra files to the image.
COPY ./root/ /

# Drop the root user and make the content of /opt/app-root owned by user 1001
RUN chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT} && \
    rpm-file-permissions

USER 1001

# Set the default CMD to print the usage of the language image
CMD $STI_SCRIPTS_PATH/usage
